### ISSUE TITLE
Form subscription are ignored

### ISSUE THREAD

**Issue by Lleios** [final-form/react-final-form-hooks#11]
## Current behavior
I specify "submitting: true" and "pristine: true" to useForm subscription and form is render all the time

## Expected Behavior
Form is render only when submitting and pristine change

[CodeSanbox](https://codesandbox.io/s/p9y9n2768j)

**Comment by erikras** [comment]
[See README](https://github.com/final-form/react-final-form-hooks#%EF%B8%8F-this-library-will-re-render-your-entire-form-on-every-state-change-as-you-type-%EF%B8%8F). This is unavailable with hooks.

**Comment by ThiefMaster** [comment]
Will it eventually be possible to use subscriptions or will the hook version never support this?

**Comment by mblarsen** [comment]
> By default, 🏁 React Final Form Hooks subscribes to all changes, but if you want to fine tune your form, you may specify only the form state that you care about for rendering your gorgeous UI.

Can you point me to an example that shows how to do this?

**Comment by mblarsen** [comment]
```
useForm({subscriptions: []})
```
Like this?
