### ISSUE TITLE
How can i set initial values?

### ISSUE THREAD

**Issue by tridungbk2010** [final-form/react-final-form-hooks#2]

**Comment by Lleios** [comment]
You can intiliaze values with :
```
useform({
  onSubmit: (values) => ({})
  initialValues: {
    key1: value,
    key2: value,
   ...
  }
})
```
or with
```
form.initialize({
    key1: value,
    key2: value,
   ...
  })

**Comment by tridungbk2010** [comment]
thanks!

**Comment by multicam** [comment]
A derived question: can I set initial values dynamically (e.g, after a field change, or a server request) -- thanks

**Comment by Lleios** [comment]
You can use form.reset, this method can set form initial values when you want

**Comment by huquduy** [comment]
sorry, how to set initialValues based on async?

**Comment by Lleios** [comment]
Use form.reset in useEffect
