### ISSUE TITLE
Field initial value `0` becomes empty string `""`

### ISSUE THREAD

**Issue by minipai** [final-form/react-final-form-hooks#22]
### What is the current behavior?

Field initial value `0` becomes empty string `""`

<img width="397" alt="screen shot 2019-02-03 at 10 39 39 am" src="https://user-images.githubusercontent.com/239570/52170542-49ec8a00-27a0-11e9-9116-a7b560732091.png">

### What is the expected behavior?

Field initial value `0` is `0`

### Sandbox Link

https://codesandbox.io/s/42o278xzq4

### What's your environment?

```
  "dependencies": {
    "final-form": "4.11.0",
    "react": "16.8.0-alpha.1",
    "react-dom": "16.8.0-alpha.1",
    "react-final-form-hooks": "1.0.0-alpha.1",
    "react-scripts": "2.0.3"
  },
```

**Comment by erikras** [comment]
Published fix in [`v1.0.0`](https://github.com/final-form/react-final-form-hooks/releases/tag/v1.0.0).
