### ISSUE TITLE
How to do checkboxes and radio controls

### ISSUE THREAD

**Issue by jkdowdle** [final-form/react-final-form-hooks#28]
Question on how to use these hooks to best suit a checkbox. It may be pretty trivial but I got confused trying to implement. 

Codesandbox 

https://codesandbox.io/s/ymoljj2qpv

```
const Form = () => {
  const { form, handleSubmit, values } = useForm({
    onSubmit: values => console.log(values),
    initialValues: { check: true }
  })
  const check = useField('text', form)
  return (
    <form onSubmit={handleSubmit}>
      <div>
        <input
          id={check.input.name}
          type="checkbox"
          value={check.input.value}
          {...check.input}
        />
        <label htmlFor={check.input.name}>
          Checkbox!
        </label>
      </div>

      <div>
        <pre>{JSON.stringify(values, null, 2)}</pre>
      </div>
    </form>
  )
}
```
Any information or direction on this would be awesome. Thank you so much for the library and if you can get any feedback to me on this I would greatly appreciate it!

**Comment by akasparovich** [comment]
Hey @jkdowdle. I've solved the issue like that: 
`
<input
          type="checkbox"
          id={check.input.name}
          checked={check.input.value}
          {...check.input}
/>
`

**Comment by jkdowdle** [comment]
@akasparovich Thank you so much for helping me out with this!

However, I can't seem to get it working. Maybe I am missing something in my useField or useForm hooks?

https://codesandbox.io/s/0m3z3wr390

**Comment by ekfn** [comment]
works on stable version
same project, just updated dependency: https://codesandbox.io/s/vxnvz5xq0

**Comment by jkdowdle** [comment]
@ekfn 

Awesome, thank you so much for pointing that out! And thanks to the maintainers for the update that fixed the issue.

**Comment by janakact** [comment]
This is very helpful <3

**Comment by bggolding** [comment]
It would be great to see this rolled into the project rather than seeing it languish as an afterthought. I wondered if it was worth adding in a different attribute for checkbox input like:

```
<input type="checkbox" {...check.checkbox} />
```

or maybe add an optional argument to useField with the input type, eg:

```
const check = useField('check', form, type='checkbox');
 [...]
<input type="checkbox" {...check.input} />
```

My feeling is hat conforms better to existing use. I wonder if there are other ways to express this that might be better?
