### ISSUE TITLE
useField pass a validate function will cause Infinite loops

### ISSUE THREAD

**Issue by chenjigeng** [final-form/react-final-form-hooks#44]
### Are you submitting a **bug report** or a **feature request**?
bug report

### Sandbox Link
https://codesandbox.io/s/m38k650n79

See the console.

### Other information
I see the source code of useField and find the reason.
![image](https://user-images.githubusercontent.com/14784326/57132477-5057c580-6dd2-11e9-8775-89578ef4a4ca.png)
In react function, every render will product new validate function.So it will cause this problem. Although we can use useCallback to avoid it.But it's so hard to use for user.Can we use useCallback in the inner or something else to solve this.

**Comment by chenjigeng** [comment]
Find another solution: Put the validate function declaration outside the render function.But if someone doesn't know the internal implementation of useField, they might make the same mistake as me

**Comment by apanizo** [comment]
@chenjigeng thanks for reporting it. I created the PR including validation at field level. Today we have discovered the bug ourselves https://github.com/iov-one/ponferrada/pull/160

I do not have too much free time these days, I will take a look and fix it as soon as I can. 

Thanks!

**Comment by apanizo** [comment]
@chenjigeng ☝️ ☝️ ☝️

**Comment by erikras** [comment]
Published fix in [`v2.0.1`](https://github.com/final-form/react-final-form-hooks/releases/tag/v2.0.1).
